"""Command-line helper for rendering a resume-fitting Codex prompt."""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import shutil
import subprocess
import sys
import sysconfig
import tempfile
from pathlib import Path
from typing import Any, Sequence


def _project_resource_path(
    *parts: str,
    module_dir: Path | None = None,
    data_dir: Path | None = None,
) -> Path:
    """Return a source-tree or installed-package resource path.

    Setuptools installs this single-module project with non-Python resources in
    the installation data directory. Source-tree runs still keep those files
    beside this module, so prefer that layout when it exists.
    """
    source_path = (module_dir or Path(__file__).resolve().parent).joinpath(*parts)
    if source_path.exists():
        return source_path

    install_data = data_dir or Path(sysconfig.get_path("data"))
    return install_data.joinpath(*parts)


TEMPLATE_PATH = _project_resource_path("resume-fitter.md")
METADATA_SCHEMA_PATH = _project_resource_path("schemas", "metadata.schema.json")
ORIGINAL_RESUME_FILENAME = "orig.tex"
TAILORED_RESUME_FILENAME = "new.tex"
METADATA_FILENAME = "metadata.json"
RUN_DIR_PREFIX = "make-my-resume-fit-"
PLACEHOLDERS = {
    "input_resume": "{{INPUT_RESUME}}",
    "job_offer_urls": "{{JOB_OFFER_URLS}}",
    "output_resume": "{{OUTPUT_RESUME}}",
}
UNRESOLVED_PLACEHOLDER_RE = re.compile(r"{{[^{}]+}}")
SAFE_SLUG_RE = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


class CodexInvocationError(RuntimeError):
    """Raised when the local Codex executable cannot complete the prompt run."""


def build_parser() -> argparse.ArgumentParser:
    """Build the CLI parser without performing any filesystem side effects."""
    parser = argparse.ArgumentParser(
        description="Render a resume-fitting prompt and run it with Codex.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=(
            "Example:\n"
            "  python make_my_resume_fit.py --original-resume resume.tex \\\n"
            "    --job-offer https://example.com/a \\\n"
            "    --job-offer https://example.com/b \\\n"
            "    --output-folder out/resume-fit \\\n"
            "    --output-name tailored-resume\n\n"
            "Pass multiple job offers by repeating --job-offer once per URL.\n\n"
            "Outputs are generated by automation and must be reviewed before use; "
            "see README.md and LICENSE for warranty and liability terms."
        ),
    )
    parser.add_argument(
        "--original-resume",
        required=True,
        type=Path,
        help="Path to the existing source resume LaTeX file (.tex).",
    )
    parser.add_argument(
        "--job-offer",
        action="append",
        required=True,
        dest="job_offers",
        metavar="URL",
        help="Job offer URL. Repeat this option to provide multiple URLs.",
    )
    parser.add_argument(
        "--output-folder",
        required=True,
        type=Path,
        help="Folder where the wrapper should copy the tailored resume output.",
    )
    parser.add_argument(
        "--output-name",
        required=True,
        help=(
            "Name for the tailored LaTeX file, without a path or extension. "
            "The wrapper writes <name>.tex."
        ),
    )
    return parser


def validate_resume_path(path: Path) -> Path:
    """Return a resolved resume path after confirming it is an existing .tex file."""
    if not path.exists():
        raise ValueError(f"original resume does not exist: {path}")
    if not path.is_file():
        raise ValueError(f"original resume is not a file: {path}")
    if path.suffix.lower() != ".tex":
        raise ValueError(f"original resume must be a .tex file: {path}")
    return path.resolve()


def ensure_output_folder(path: Path) -> Path:
    """Create the output folder if needed and return its resolved path."""
    if path.exists() and not path.is_dir():
        raise ValueError(f"output folder is not a directory: {path}")
    try:
        path.mkdir(parents=True, exist_ok=True)
    except OSError as exc:
        raise ValueError(f"could not create output folder {path}: {exc}") from exc
    return path.resolve()


def build_output_resume_filename(output_name: str) -> str:
    """Return the temp-local .tex filename for a validated output stem."""
    name = output_name.strip()
    if not name:
        raise ValueError("output name must not be empty")
    if name in {".", ".."}:
        raise ValueError("output name must be a filename, not a directory reference")
    if any(separator and separator in name for separator in {os.sep, os.altsep, "/", "\\"}):
        raise ValueError("output name must not contain path separators")
    if Path(name).suffix:
        raise ValueError("output name must not include a file extension")
    return f"{name}.tex"


def create_run_workspace(
    original_resume: Path,
    *,
    temp_root: Path | None = None,
    timestamp: dt.datetime | None = None,
) -> Path:
    """Create an isolated temp run directory and copy the resume to orig.tex."""
    root = Path(temp_root) if temp_root is not None else Path(tempfile.gettempdir())
    stamp = (timestamp or dt.datetime.now()).strftime("%Y%m%dT%H%M%S%f")

    # The timestamp is enough for normal runs; the suffix handles deterministic
    # tests, clock collisions, and concurrent invocations in the same microsecond.
    for suffix in ["", *[f"-{index:02d}" for index in range(1, 100)]]:
        run_dir = root / f"{RUN_DIR_PREFIX}{stamp}{suffix}"
        try:
            run_dir.mkdir(parents=True, exist_ok=False)
        except FileExistsError:
            continue
        shutil.copyfile(original_resume, run_dir / ORIGINAL_RESUME_FILENAME)
        return run_dir.resolve()

    raise ValueError(f"could not create a unique temp run directory under {root}")


def load_template(path: Path = TEMPLATE_PATH) -> str:
    """Load the prompt template from disk."""
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        raise ValueError(f"template file not found: {path}") from exc


def format_job_offers(job_offers: Sequence[str]) -> str:
    """Format repeated job-offer arguments as a deterministic Markdown list."""
    return "\n".join(f"- {url}" for url in job_offers)


def render_template(
    template: str,
    *,
    input_resume: str = ORIGINAL_RESUME_FILENAME,
    job_offers: Sequence[str],
    output_resume: str = TAILORED_RESUME_FILENAME,
) -> str:
    """Replace all known placeholders and reject unresolved template markers."""
    rendered = (
        template.replace(PLACEHOLDERS["input_resume"], input_resume)
        .replace(PLACEHOLDERS["job_offer_urls"], format_job_offers(job_offers))
        .replace(PLACEHOLDERS["output_resume"], output_resume)
    )
    unresolved = UNRESOLVED_PLACEHOLDER_RE.findall(rendered)
    if unresolved:
        names = ", ".join(sorted(set(unresolved)))
        raise ValueError(f"template contains unresolved placeholders: {names}")
    return rendered


def build_codex_command(run_dir: Path) -> list[str]:
    """Return the sandboxed Codex command used to consume the prompt on stdin."""
    resolved_run_dir = run_dir.resolve()
    return [
        "codex",
        "--search",
        "-c",
        "sandbox_workspace_write.network_access=true",
        "exec",
        "--sandbox",
        "workspace-write",
        "--skip-git-repo-check",
        "-C",
        str(resolved_run_dir),
        "--output-schema",
        str(METADATA_SCHEMA_PATH.resolve()),
        "-o",
        str(resolved_run_dir / METADATA_FILENAME),
        "-",
    ]


def invoke_codex(prompt: str, *, run_dir: Path) -> None:
    """Invoke Codex with the rendered prompt via stdin."""
    command = build_codex_command(run_dir)
    try:
        completed = subprocess.run(
            command,
            input=prompt,
            text=True,
            check=False,
        )
    except FileNotFoundError as exc:
        raise CodexInvocationError(
            "Codex executable not found. Ensure `codex` is installed and on PATH."
        ) from exc
    except OSError as exc:
        raise CodexInvocationError(f"failed to invoke Codex: {exc}") from exc

    if completed.returncode != 0:
        raise CodexInvocationError(
            f"Codex command failed with exit code {completed.returncode}."
        )


def validate_generated_resume(
    run_dir: Path,
    output_resume: str = TAILORED_RESUME_FILENAME,
) -> Path:
    """Return the temp output resume path after confirming Codex produced it."""
    generated_resume = run_dir / output_resume
    if not generated_resume.is_file():
        raise CodexInvocationError(
            f"Codex completed without producing {output_resume} in {run_dir}."
        )
    return generated_resume


def load_metadata_schema(path: Path = METADATA_SCHEMA_PATH) -> dict[str, Any]:
    """Load the repository-owned metadata schema used for local validation."""
    try:
        schema = json.loads(path.read_text(encoding="utf-8"))
    except FileNotFoundError as exc:
        raise CodexInvocationError(f"metadata schema file not found: {path}") from exc
    except json.JSONDecodeError as exc:
        raise CodexInvocationError(f"metadata schema file is malformed JSON: {exc}") from exc
    if not isinstance(schema, dict):
        raise CodexInvocationError("metadata schema file must contain a JSON object.")
    return schema


def _type_name(value: Any) -> str:
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, dict):
        return "object"
    if isinstance(value, list):
        return "array"
    if isinstance(value, str):
        return "string"
    if value is None:
        return "null"
    if isinstance(value, (int, float)):
        return "number"
    return type(value).__name__


def _validate_schema_subset(value: Any, schema: dict[str, Any], path: str) -> list[str]:
    """Validate the focused JSON Schema subset used by schemas/metadata.schema.json."""
    errors: list[str] = []
    expected_type = schema.get("type")
    if expected_type == "object":
        if not isinstance(value, dict):
            return [f"{path} must be an object, got {_type_name(value)}"]

        required = schema.get("required", [])
        if isinstance(required, list):
            for key in required:
                if isinstance(key, str) and key not in value:
                    errors.append(f"{path}.{key} is required")

        properties = schema.get("properties", {})
        if isinstance(properties, dict):
            for key, item in value.items():
                if key in properties and isinstance(properties[key], dict):
                    errors.extend(
                        _validate_schema_subset(item, properties[key], f"{path}.{key}")
                    )
                elif schema.get("additionalProperties") is False:
                    errors.append(f"{path}.{key} is not allowed")
        return errors

    if expected_type == "array":
        if not isinstance(value, list):
            return [f"{path} must be an array, got {_type_name(value)}"]

        item_schema = schema.get("items")
        if isinstance(item_schema, dict):
            for index, item in enumerate(value):
                errors.extend(_validate_schema_subset(item, item_schema, f"{path}[{index}]"))
        return errors

    if expected_type == "string":
        if not isinstance(value, str):
            return [f"{path} must be a string, got {_type_name(value)}"]

        pattern = schema.get("pattern")
        if isinstance(pattern, str) and re.fullmatch(pattern, value) is None:
            errors.append(f"{path} must match pattern {pattern}")
        return errors

    return errors


def validate_metadata_json(
    metadata_path: Path,
    schema_path: Path = METADATA_SCHEMA_PATH,
    *,
    expected_job_offers: Sequence[str] | None = None,
) -> dict[str, Any]:
    """Return parsed metadata.json after checking presence, JSON syntax, and schema shape."""
    if not metadata_path.is_file():
        raise CodexInvocationError(
            f"Codex completed without producing structured output {METADATA_FILENAME}."
        )

    raw_metadata = metadata_path.read_text(encoding="utf-8")
    if not raw_metadata.strip():
        raise CodexInvocationError(f"Codex produced empty structured output {METADATA_FILENAME}.")

    try:
        metadata = json.loads(raw_metadata)
    except json.JSONDecodeError as exc:
        raise CodexInvocationError(
            f"Codex produced malformed JSON in {METADATA_FILENAME}: {exc}"
        ) from exc

    schema = load_metadata_schema(schema_path)
    errors = _validate_schema_subset(metadata, schema, "$")
    if errors:
        joined = "; ".join(errors)
        raise CodexInvocationError(
            f"Codex structured output {METADATA_FILENAME} does not match schema: {joined}"
        )

    if expected_job_offers is not None:
        actual_job_offers = metadata.get("job_offer_urls")
        expected = list(expected_job_offers)
        if actual_job_offers != expected:
            raise CodexInvocationError(
                f"Codex structured output {METADATA_FILENAME} does not include the "
                "supplied job-offer URLs exactly as provided."
            )

    return metadata


def validate_metadata_slug(metadata: dict[str, Any]) -> str:
    """Return the validated archive slug from metadata.json.

    The schema already enforces this today, but keeping the runtime guard close
    to filesystem publication prevents future schema loosening from creating
    unsafe archive paths.
    """
    slug = metadata.get("slug")
    if not isinstance(slug, str) or SAFE_SLUG_RE.fullmatch(slug) is None:
        raise CodexInvocationError(
            f"Codex structured output {METADATA_FILENAME} does not contain a usable slug."
        )
    return slug


def create_archive_directory(
    output_folder: Path,
    slug: str,
    *,
    current_date: dt.date | None = None,
) -> Path:
    """Create and return the next dated, versioned archive directory."""
    if not isinstance(slug, str) or SAFE_SLUG_RE.fullmatch(slug) is None:
        raise CodexInvocationError(f"archive slug is not filesystem safe: {slug!r}")

    output = ensure_output_folder(output_folder)
    archive_date = current_date or dt.date.today()
    archive_prefix = archive_date.isoformat()

    for version in range(1, 1000):
        archive_dir = output / f"{archive_prefix}-v{version}-{slug}"
        try:
            archive_dir.mkdir(exist_ok=False)
        except FileExistsError:
            continue
        return archive_dir.resolve()

    raise CodexInvocationError(
        f"could not create a unique archive directory under {output} for slug {slug!r}."
    )


def copy_final_artifacts(
    generated_resume: Path,
    original_resume: Path,
    metadata: dict[str, Any],
    output_folder: Path,
    *,
    current_date: dt.date | None = None,
) -> Path:
    """Publish validated temp artifacts to a dated archive directory."""
    slug = validate_metadata_slug(metadata)
    archive_dir = create_archive_directory(
        output_folder,
        slug,
        current_date=current_date,
    )
    try:
        shutil.copyfile(generated_resume, archive_dir / generated_resume.name)
        shutil.copyfile(original_resume, archive_dir / ORIGINAL_RESUME_FILENAME)
        (archive_dir / METADATA_FILENAME).write_text(
            json.dumps(metadata, indent=2) + "\n",
            encoding="utf-8",
        )
    except OSError:
        shutil.rmtree(archive_dir, ignore_errors=True)
        raise
    return archive_dir


def run(argv: Sequence[str] | None = None) -> int:
    """Parse arguments, render the prompt, and invoke Codex."""
    parser = build_parser()
    args = parser.parse_args(argv)

    try:
        original_resume = validate_resume_path(args.original_resume)
        output_resume = build_output_resume_filename(args.output_name)
        run_dir = create_run_workspace(original_resume)
        template = load_template()
        prompt = render_template(
            template,
            input_resume=ORIGINAL_RESUME_FILENAME,
            job_offers=args.job_offers,
            output_resume=output_resume,
        )
        invoke_codex(prompt, run_dir=run_dir)
        generated_resume = validate_generated_resume(run_dir, output_resume)
        metadata = validate_metadata_json(
            run_dir / METADATA_FILENAME,
            expected_job_offers=args.job_offers,
        )
        copy_final_artifacts(
            generated_resume,
            run_dir / ORIGINAL_RESUME_FILENAME,
            metadata,
            args.output_folder,
        )
    except ValueError as exc:
        parser.error(str(exc))
    except CodexInvocationError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    return 0


def main() -> None:
    """Console-script entry point."""
    raise SystemExit(run())


if __name__ == "__main__":
    main()
